server:
  port: 8182

spring:
  datasource:
    name: dev
    url: jdbc:mysql://localhost:3306/firstdb?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: guoguo841268
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.example.Review.domain